In [7]:
class Employee:

    empCount = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.empCount += 1

    def employeeCount():
        return Employee.empCount

    def average_salary(self, totalSalary, totalEmployees):
        if totalEmployees == 0:
            return 0
        return totalSalary / totalEmployees



class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, hoursWorked):
        super().__init__(name, family, salary, department)


        self.hoursWorked = hoursWorked


# Employee
emp1 = Employee("Ashritha", "Reddy", 50000, "Computer Science")
emp2 = Employee("Jyothsna", "Reddy", 60000, "Data Science")

# full time employee

fEmp1 = FulltimeEmployee("Abhinav", "Roy", 80000, "Artificial Intelligence", 10)
fEmp2 = FulltimeEmployee("Rohit", "Chowdary", 90000, "Cyber", 12)


print(f"Total employees: {Employee.employeeCount()}")

print(f"Employee: {emp1.name}, Family: {emp1.family}, Salary: {emp1.salary}, Department: {emp1.department}")
print(f"Employee: {emp2.name}, Family: {emp2.family}, Salary: {emp2.salary}, Department: {emp2.department}")

print(f"Fulltime Employee: {fEmp1.name}, Family: {fEmp1.family}, Salary: {fEmp1.salary}, Department: {fEmp1.department}, Hours Worked: {fEmp1.hoursWorked}")
print(f"Fulltime Employee: {fEmp2.name}, Family: {fEmp2.family}, Salary: {fEmp2.salary}, Department: {fEmp2.department}, Hours Worked: {fEmp2.hoursWorked}")

totalSalary = emp1.salary + emp2.salary + fEmp1.salary + fEmp2.salary
totalEmployees = Employee.employeeCount()
average = emp1.average_salary(totalSalary, totalEmployees)
print(f"Average salary: {average}")



Total employees: 4
Employee: Ashritha, Family: Reddy, Salary: 50000, Department: Computer Science
Employee: Jyothsna, Family: Reddy, Salary: 60000, Department: Data Science
Fulltime Employee: Abhinav, Family: Roy, Salary: 80000, Department: Artificial Intelligence, Hours Worked: 10
Fulltime Employee: Rohit, Family: Chowdary, Salary: 90000, Department: Cyber, Hours Worked: 12
Average salary: 70000.0


In [9]:
import numpy as np

input = np.random.uniform(1, 20, 20)

matrix = input.reshape(4, 5)

print("Original matrix:")
print(matrix)

r1 = np.arange(matrix.shape[0])
c1 = matrix.argmax(axis=1)

matrix[r1, c1] = 0


print("Final matrix:")
print(matrix)


Original matrix:
[[10.88585516  3.20645882 16.93169792  4.22430151  8.96470576]
 [ 8.5131148   3.91455673  3.62769457  9.92890978 12.79210527]
 [ 3.92998752  2.56670013 10.32783803 19.32568947 12.34474304]
 [18.85644909 17.72564156 17.43261539  8.39332843  9.58294931]]
Final matrix:
[[10.88585516  3.20645882  0.          4.22430151  8.96470576]
 [ 8.5131148   3.91455673  3.62769457  9.92890978  0.        ]
 [ 3.92998752  2.56670013 10.32783803  0.         12.34474304]
 [ 0.         17.72564156 17.43261539  8.39332843  9.58294931]]
